---
title: Módulo 4
authors: 
  - name: Juan Pablo Siracusa
    department: Department of Industrial Enginnering
    affiliation: Facultad de Ingenieria UNCUYO
    location: Mendoza, Argentina
    email: jpsb2013@gmail.com 
  - name: Mariana Mut
    department: Department of Industrial Enginnering
    affiliation: Facultad de Ingenieria UNCUYO 
    location: Mendoza, Argentina
    email: mutmariana04@gmail.com 
  - name: Isabella Morandini Monteverdi
    department: Department of Industrial Enginnering
    affiliation: Facultad de Ingenieria UNCUYO
    location: Mendoza, Argentina
    email: isa.morandini03@gmail.com 
  - name: Ana Gordillo
    Department: Department of Industrial Enginnering
    affiliation: Facultad de Ingenieria UNCUYO
    location: Mendoza, Argentina
    email: gordilloa121@gmail.com 
  - name: Genovese Luciano
    department: Department of Industrial Enginnering
    affiliation: Facultad de Ingenieria UNCUYO
    location: Mendoza, Argentina
    email: luchogenovese8@gmail.com 
  - name: Tomás Raby
    department: Department of Industrial Enginnering
    affiliation: Facultad de Ingenieria UNCUYO
    location: Mendoza, Argentina
    email: tomyraby@gmail.com 
abstract: |
  Enter the text of your abstract here.
bibliography: references.bib
biblio-style: apa
output: rticles::arxiv_article
---



## Introducción a los papers
Para analizar la estructura de un paper buscamos un ejemplo a la aplicación de los gemelos digitales.
Este trata sobre como nos podemos beneficiar de los motores de juego para desarrollar gemelos digitales que sirvan para planificar el despliegue de la energía fotovoltaica.

Este estudio investiga el uso de motores de juego para crear gemelos digitales (DT) de sistemas fotovoltaicos (FV). Los motores de juego son esencialmente simuladores en tiempo real que procesan las entradas del usuario y ajustan un mundo virtual en consecuencia.  Los autores sostienen que características como los gráficos avanzados y los motores de física los hacen útiles para aplicaciones de ingeniería.

Se centraron en la creación de un prototipo mínimo viable de un sistema fotovoltaico para tejados residenciales. Debido a la naturaleza de prototipo, optaron por un comportamiento simulado (Digital Mock-Up - DM) dentro del motor de juegos Unreal Engine 5 (UE5).  Eligieron UE5 por sus gráficos superiores y sus características de uso gratuito hasta un determinado umbral de ingresos.

El prototipo incluía un campo fotovoltaico de 16 módulos que representaba un sistema doméstico típico.  Para simplificar el modelo, asumieron condiciones de prueba estándar y no incluyeron factores como inversores o baterías que estarían presentes en un sistema del mundo real.

Además de UE5, utilizaron varias funciones de UE5 y recursos del mercado para crear la casa, el entorno y los módulos fotovoltaicos personalizados. También utilizaron la función de planos de UE5 para programar el comportamiento dentro de la simulación.
  


## Referencias Bibliográficas

Clausen, C. S. B., Ma, Z. G., & Jørgensen, B. N. (2022). Can we benefit from game engines to develop digital twins for planning the deployment of photovoltaics?. Energy Informatics, 5(Suppl 4), 42.